name: build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_docker_image_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
    - name: Get short git hash
      id: short_hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Get version
      id: get_version
      run: echo "::set-output name=version::$(grep '^ARG VERSION=' Dockerfile  | cut -d= -f2)"
    - name: Get docker metadata
      id: get_metadata
      uses: docker/metadata-action@f3c886e26b64d7e5ef5ff5f574efc88b317b8451
      with:
        images: willholtz/test-tag
    - name: dump tags
      id: dump_tags
      run: echo tags: ${{ steps.get_metadata.outputs.tags }}; labels: ${{ steps.meta.outputs.labels }}
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
    - name: Login to DockerHub
      uses: docker/login-action@17f28ab24d0d2832d5ff23a1409bbfc373ebcb96
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@fe02965b4878556fce19e4f0aa608d7d09ed629b
      with:
        platforms: linux/amd64
        push: true
        tags: ${{ steps.get_metadata.outputs.tags }}
        labels: ${{ steps.get_metadata.outputs.labels}}
